---
# Global variables for all hosts

# Network Configuration
network_config:
  ipv6_disabled: true
  static_ip_enabled: true
  dhcp_enabled: false
  interface: eth0
  gateway: "192.168.1.1"
  dns_servers:
    - "8.8.8.8"
    - "8.8.4.4"
  ip_pool:
    - "192.168.1.10"
    - "192.168.1.11"
    - "192.168.1.12"
    - "192.168.1.13"
    - "192.168.1.14"
    - "192.168.1.15"
    - "192.168.1.16"
    - "192.168.1.17"
    - "192.168.1.18"
    - "192.168.1.19"

# System Configuration
system_config:
  hostname_format: "{{ inventory_hostname }}"
  timezone: "UTC"
  locale: "en_US.UTF-8"
  ntp_enabled: true
  ntp_servers:
    - "pool.ntp.org"
    - "time.google.com"
  swap_size: "2G"
  kernel_params:
    - "net.ipv4.tcp_syncookies=1"
    - "net.ipv4.tcp_max_syn_backlog=2048"
    - "net.core.somaxconn=65535"
    - "vm.swappiness=10"

# Package Management
package_config:
  update_cache: true
  upgrade_packages: true
  remove_unused: true
  essential_packages:
    - "curl"
    - "wget"
    - "vim"
    - "htop"
    - "unzip"
    - "apt-transport-https"
    - "ca-certificates"
    - "gnupg"
    - "lsb-release"
    - "software-properties-common"
    - "fail2ban"
    - "ufw"
    - "logrotate"
    - "rsyslog"

# Security Configuration
security_config:
  level: "high"
  ssh_config:
    port: 22
    permit_root_login: false
    password_authentication: false
    pubkey_authentication: true
    max_auth_tries: 3
    client_alive_interval: 300
    client_alive_count_max: 2
    allow_users: "debian"
    deny_users: "root"
  firewall_config:
    enabled: true
    default_policy: "DROP"
    allowed_ports:
      - "22/tcp"
      - "80/tcp"
      - "443/tcp"
    allowed_networks:
      - "192.168.1.0/24"
  fail2ban_config:
    enabled: true
    bantime: 3600
    findtime: 600
    maxretry: 3
  audit_config:
    enabled: true
    rules_file: "/etc/audit/rules.d/ansible.rules"

# Docker Configuration
docker_config:
  version: "latest"
  compose_version: "v2.20.0"
  storage_driver: "overlay2"
  daemon_config:
    storage_driver: "overlay2"
    log_driver: "json-file"
    log_opts:
      max-size: "10m"
      max-file: "3"
    default_ulimits:
      nofile:
        name: nofile
        soft: 64000
        hard: 64000
    live_restore: true
    userland_proxy: false
    ip_forward: true
    iptables: true
    bridge: "docker0"
    default_address_pools:
      - base: "172.17.0.0/12"
        size: 16

# Monitoring Configuration
monitoring_config:
  enabled: true
  log_aggregation: true
  metrics_collection: true
  alerting_enabled: true
  log_retention_days: 30
  monitoring_packages:
    - "prometheus-node-exporter"
    - "htop"
    - "iotop"
    - "nethogs"

# Backup Configuration
backup_config:
  enabled: true
  retention_days: 30
  backup_directories:
    - "/etc"
    - "/var/log"
    - "/home"
  exclude_patterns:
    - "*.tmp"
    - "*.log"
    - "/tmp/*"
    - "/var/tmp/*"

# User Management
user_config:
  admin_user: "debian"
  sudo_group: "sudo"
  create_admin_user: true
  admin_ssh_keys: []
  password_expiry_days: 90
  min_password_length: 12

# CIS Benchmark Configuration
cis_config:
  enabled: true
  level: "2"  # Level 1 or 2
  sections:
    - "1.1.1"
    - "1.1.2"
    - "1.1.3"
    - "1.2.1"
    - "1.2.2"
    - "1.2.3"
    - "1.3.1"
    - "1.3.2"
    - "1.4.1"
    - "1.4.2"
    - "1.4.3"
    - "1.5.1"
    - "1.5.2"
    - "1.5.3"
    - "1.5.4"
    - "1.6.1"
    - "1.6.2"
    - "1.6.3"
    - "1.6.4"
    - "1.7.1"
    - "1.7.2"
    - "1.7.3"
    - "1.7.4"
    - "1.7.5"
    - "1.7.6"
    - "1.8.1"
    - "1.8.2"
    - "1.8.3"
    - "1.8.4"
    - "1.9.1"
    - "1.9.2"
    - "1.9.3"
    - "1.9.4"
    - "1.9.5"
    - "1.9.6"
    - "1.9.7"
    - "1.9.8"
    - "1.9.9"
    - "1.9.10"
    - "1.9.11"
    - "1.9.12"
    - "1.9.13"
    - "1.9.14"
    - "1.9.15"
    - "1.9.16"
    - "1.9.17"
    - "1.9.18"
    - "1.9.19"
    - "1.9.20"
    - "1.9.21"
    - "1.9.22"
    - "1.9.23"
    - "1.9.24"
    - "1.9.25"
    - "1.9.26"
    - "1.9.27"
    - "1.9.28"
    - "1.9.29"
    - "1.9.30"
    - "1.9.31"
    - "1.9.32"
    - "1.9.33"
    - "1.9.34"
    - "1.9.35"
    - "1.9.36"
    - "1.9.37"
    - "1.9.38"
    - "1.9.39"
    - "1.9.40"
    - "1.9.41"
    - "1.9.42"
    - "1.9.43"
    - "1.9.44"
    - "1.9.45"
    - "1.9.46"
    - "1.9.47"
    - "1.9.48"
    - "1.9.49"
    - "1.9.50"
    - "1.9.51"
    - "1.9.52"
    - "1.9.53"
    - "1.9.54"
    - "1.9.55"
    - "1.9.56"
    - "1.9.57"
    - "1.9.58"
    - "1.9.59"
    - "1.9.60"
    - "1.9.61"
    - "1.9.62"
    - "1.9.63"
    - "1.9.64"
    - "1.9.65"
    - "1.9.66"
    - "1.9.67"
    - "1.9.68"
    - "1.9.69"
    - "1.9.70"
    - "1.9.71"
    - "1.9.72"
    - "1.9.73"
    - "1.9.74"
    - "1.9.75"
    - "1.9.76"
    - "1.9.77"
    - "1.9.78"
    - "1.9.79"
    - "1.9.80"
    - "1.9.81"
    - "1.9.82"
    - "1.9.83"
    - "1.9.84"
    - "1.9.85"
    - "1.9.86"
    - "1.9.87"
    - "1.9.88"
    - "1.9.89"
    - "1.9.90"
    - "1.9.91"
    - "1.9.92"
    - "1.9.93"
    - "1.9.94"
    - "1.9.95"
    - "1.9.96"
    - "1.9.97"
    - "1.9.98"
    - "1.9.99"
    - "1.9.100"

# Environment-specific variables
backup_enabled: true
monitoring_level: "detailed" 